import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { DataTable } from "mantine-datatable";
import { Badge } from "@mantine/core";
import { useRouter } from "next/router";

export const getServerSideProps: GetServerSideProps = async (_) => ({
  props: {
    layoutType: "dashboard",
  },
});

const Dashboard: NextPage = () => {
  const router = useRouter();
  const EXAMPLE = [
    {
      chain: "Ethereum",
      address: "0xDbe86ffb79198aDC59574c65F8D9132e269eDE81",
      reward: 1234,
    },
    {
      chain: "Polygon",
      address: "0xDbe86ffb79198aDC59574c65F8D9132e269eDE82",
      reward: 1234,
    },
  ];

  const getChainColor = (chain: string) => {
    if (chain === "Ethereum") return "dark";
    if (chain === "Polygon") return "pink";
    return "";
  };

  const getTableData = () => {
    return {
      columns: [
        {
          accessor: "chain",
          render: ({ chain }: { chain: string }) => (
            <Badge color={getChainColor(chain)} radius="sm">
              {chain.slice(0, 3).toUpperCase()}
            </Badge>
          ),
        },
        {
          accessor: "address",
        },
        {
          accessor: "reward",
        },
      ],
      records: EXAMPLE,
    };
  };
  return (
    <div className="h-full w-full">
      <Head>
        <title>Dashboard | DeCartography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col w-full align-center">
        <DataTable
          columns={getTableData().columns}
          records={getTableData().records}
          idAccessor="address"
          className="cursor-pointer"
          withBorder
          borderRadius="sm"
          withColumnBorders
          striped
          highlightOnHover
          onRowClick={({ address }) => {
            router.push("dashboard/" + address);
          }}
        />
      </main>
    </div>
  );
};

export default Dashboard;
